LOG_COLUMNS = ["FASE", "STEP", "F_Ini", "F_Fin", "Length", "TIPO"]

STOP_WORDS_ES = {
    "a",
    "al",
    "algo",
    "algunos",
    "ante",
    "antes",
    "aquel",
    "aquella",
    "aquellas",
    "aquello",
    "aquellos",
    "aqui",
    "as",
    "asi",
    "aun",
    "aunque",
    "bajo",
    "bien",
    "cada",
    "casi",
    "como",
    "con",
    "contra",
    "cual",
    "cuales",
    "cuando",
    "de",
    "del",
    "desde",
    "donde",
    "dos",
    "el",
    "ella",
    "ellas",
    "ello",
    "ellos",
    "en",
    "entre",
    "era",
    "erais",
    "eran",
    "eras",
    "eres",
    "es",
    "esa",
    "esas",
    "ese",
    "eso",
    "esos",
    "esta",
    "estaba",
    "estabais",
    "estaban",
    "estabas",
    "estad",
    "estada",
    "estadas",
    "estado",
    "estados",
    "estais",
    "estamos",
    "estando",
    "estar",
    "estaremos",
    "estará",
    "estarán",
    "estarás",
    "estaré",
    "estaréis",
    "estaría",
    "estaríais",
    "estaríamos",
    "estarían",
    "estarías",
    "estas",
    "este",
    "estemos",
    "esto",
    "estos",
    "estoy",
    "estuve",
    "estuviera",
    "estuvierais",
    "estuvieran",
    "estuvieras",
    "estuvieron",
    "estuviese",
    "estuvieseis",
    "estuviesen",
    "estuvieses",
    "estuvimos",
    "estuviste",
    "estuvisteis",
    "estuvo",
    "está",
    "estábamos",
    "estáis",
    "están",
    "estás",
    "esté",
    "estéis",
    "estén",
    "estés",
    "fue",
    "fuera",
    "fuerais",
    "fueran",
    "fueras",
    "fueron",
    "fuese",
    "fueseis",
    "fuesen",
    "fueses",
    "fui",
    "fuimos",
    "fuiste",
    "fuisteis",
    "ha",
    "habia",
    "habéis",
    "haber",
    "había",
    "habíais",
    "habíamos",
    "habían",
    "habías",
    "han",
    "has",
    "hasta",
    "hay",
    "he",
    "hemos",
    "hube",
    "hubiera",
    "hubierais",
    "hubieran",
    "hubieras",
    "hubieron",
    "hubiese",
    "hubieseis",
    "hubiesen",
    "hubieses",
    "hubimos",
    "hubiste",
    "hubisteis",
    "hubo",
    "la",
    "las",
    "le",
    "les",
    "lo",
    "los",
    "mas",
    "me",
    "mi",
    "mis",
    "mucho",
    "muchos",
    "muy",
    "más",
    "mí",
    "mía",
    "mías",
    "mío",
    "míos",
    "nada",
    "ni",
    "no",
    "nos",
    "nosotras",
    "nosotros",
    "nuestra",
    "nuestras",
    "nuestro",
    "nuestros",
    "o",
    "os",
    "otra",
    "otras",
    "otro",
    "otros",
    "para",
    "pero",
    "poco",
    "por",
    "porque",
    "que",
    "quien",
    "quienes",
    "qué",
    "se",
    "sea",
    "seais",
    "sean",
    "seas",
    "ser",
    "será",
    "serán",
    "serás",
    "seré",
    "seréis",
    "sería",
    "seríais",
    "seríamos",
    "serían",
    "serías",
    "si",
    "sido",
    "siendo",
    "sin",
    "sobre",
    "sois",
    "somos",
    "son",
    "soy",
    "su",
    "sus",
    "suya",
    "suyas",
    "suyo",
    "suyos",
    "sí",
    "tambien",
    "también",
    "tan",
    "tanto",
    "te",
    "tendremos",
    "tendrá",
    "tendrán",
    "tendrás",
    "tendré",
    "tendréis",
    "tendría",
    "tendríais",
    "tendríamos",
    "tendrían",
    "tendrías",
    "tened",
    "tenemos",
    "tenga",
    "tengais",
    "tengan",
    "tengas",
    "tengo",
    "tenida",
    "tenidas",
    "tenido",
    "tenidos",
    "teniendo",
    "tenéis",
    "tenía",
    "teníais",
    "teníamos",
    "tenían",
    "tenías",
    "ti",
    "tiene",
    "tienen",
    "tienes",
    "todo",
    "todos",
    "tu",
    "tus",
    "tuve",
    "tuviera",
    "tuvierais",
    "tuvieran",
    "tuvieras",
    "tuvieron",
    "tuviese",
    "tuvieseis",
    "tuviesen",
    "tuvieses",
    "tuvimos",
    "tuviste",
    "tuvisteis",
    "tuvo",
    "tuya",
    "tuyas",
    "tuyo",
    "tuyos",
    "tú",
    "un",
    "una",
    "uno",
    "unos",
    "vosotras",
    "vosotros",
    "vuestra",
    "vuestras",
    "vuestro",
    "vuestros",
    "y",
    "ya",
}

STOP_WORDS_EN = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "but",
    "by",
    "for",
    "from",
    "has",
    "have",
    "he",
    "her",
    "his",
    "i",
    "in",
    "is",
    "it",
    "its",
    "me",
    "my",
    "not",
    "of",
    "on",
    "or",
    "our",
    "she",
    "so",
    "that",
    "the",
    "their",
    "them",
    "there",
    "they",
    "this",
    "to",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "who",
    "will",
    "with",
    "you",
    "your",
}



SANDERSON_TERMS = {
        "Adin": "Personaje",
    "Adolin": "Personaje",
    "Alanik": "Personaje",
    "Alcatraz Smedry": "Personaje",
    "Allriandre Durkel": "Personaje",
    "Allrianne Cett": "Personaje",
    "Anthony Davis": "Personaje",
    "Ashweather Cett": "Personaje",
    "Axies": "Personaje",
    "Balat Davar": "Personaje",
    "Bastille": "Personaje",
    "Baxil": "Personaje",
    "Brade Shimabukuro": "Personaje",
    "Briggen": "Personaje",
    "Cenn": "Personaje",
    "Chiri-Chiri": "Personaje",
    "Cikatriz": "Personaje",
    "Cuna": "Personaje",
    "Dabbid": "Personaje",
    "Daggon": "Personaje",
    "Dalinar": "Personaje",
    "David Charleston": "Personaje",
    "Dedelin": "Personaje",
    "Dieno": "Personaje",
    "Dilaf": "Personaje",
    "Dockson": "Personaje",
    "Dyel": "Personaje",
    "Edgard Ladrian": "Personaje",
    "Edwarn Ladrian": "Personaje",
    "Elegía Salvamento": "Personaje",
    "Elend": "Personaje",
    "Elhokar": "Personaje",
    "Ellista": "Personaje",
    "Eshonai": "Personaje",
    "Fantasma": "Personaje",
    "Fatren": "Personaje",
    "Fen": "Personaje",
    "Fjon": "Personaje",
    "Frava": "Personaje",
    "Freya Marten": "Personaje",
    "Galladon": "Personaje",
    "Gaotona": "Personaje",
    "Gavilar": "Personaje",
    "Gaz": "Personaje",
    "Geranid": "Personaje",
    "Hauka": "Personaje",
    "Hershel Black": "Personaje",
    "Hesina": "Personaje",
    "Hoid": "Personaje",
    "Hrathen": "Personaje",
    "Irich": "Personaje",
    "Ishikk": "Personaje",
    "Jasnah": "Personaje",
    "Jordis": "Personaje",
    "Jorgen": "Personaje",
    "Judy Ivans": "Personaje",
    "Kaladin": "Personaje",
    "Kalak": "Personaje",
    "Kar": "Personaje",
    "Karith Marvudi": "Personaje",
    "Kaza": "Personaje",
    "Kelsier": "Personaje",
    "Kenton": "Personaje",
    "Khrissalla": "Personaje",
    "Kimmalyn": "Personaje",
    "La-Verdad-Espera": "Personaje",
    "Languish": "Personaje",
    "Lem": "Personaje",
    "Lezian": "Personaje",
    "Lhan": "Personaje",
    "Lifeforce": "Personaje",
    "Lift": "Personaje",
    "Lilly Whiting": "Personaje",
    "Lirin": "Personaje",
    "Lopen": "Personaje",
    "Lukel": "Personaje",
    "M-Bot": "Personaje",
    "Marasi": "Personaje",
    "Marsh": "Personaje",
    "Matisse": "Personaje",
    "MeLaan": "Personaje",
    "Mem": "Personaje",
    "Mennis": "Personaje",
    "Amaram": "Personaje",
    "Migs": "Personaje",
    "Miles Dagouter": "Personaje",
    "Moash": "Personaje",
    "Morriumur": "Personaje",
    "Mraize": "Personaje",
    "Nale": "Personaje",
    "Navani": "Personaje",
    "Nedd Strong": "Personaje",
    "Nikaro": "Personaje",
    "Nikliasorm": "Personaje",
    "Lunamor": "Personaje",
    "Paige": "Personaje",
    "Palona": "Personaje",
    "Philen Frandeu": "Personaje",
    "Prasanva": "Personaje",
    "Puuli": "Personaje",
    "Ranette": "Personaje",
    "Raoden": "Personaje",
    "Rebecca Nightshade": "Personaje",
    "Renarin": "Personaje",
    "Rlain": "Personaje",
    "Rodge McCaffrey": "Personaje",
    "Rysn Ftori": "Personaje",
    "Sarene": "Personaje",
    "Sazed": "Personaje",
    "Shalash": "Personaje",
    "Shallan": "Personaje",
    "Sheler": "Personaje",
    "Sigzil": "Personaje",
    "Silencio Montane": "Personaje",
    "Sisirinah": "Personaje",
    "Sexto del Ocaso": "Personaje",
    "Sja-anat": "Personaje",
    "Spensa": "Personaje",
    "Sondeluz": "Personaje",
    "Stephen Leeds": "Personaje",
    "Steris": "Personaje",
    "Straff": "Personaje",
    "Syl": "Personaje",
    "Szeth": "Personaje",
    "Talenel": "Personaje",
    "Tanavast": "Personaje",
    "Taravangian": "Personaje",
    "Teft": "Personaje",
    "Telsin Ladrian": "Personaje",
    "Templeton Fig": "Personaje",
    "TenSoon": "Personaje",
    "Themos Tresting": "Personaje",
    "Sadeas": "Personaje",
    "Trenza": "Personaje",
    "Valizode": "Personaje",
    "Vasher": "Personaje",
    "Venli": "Personaje",
    "Humano": "Personaje",
    "Vin": "Personaje",
    "Vivenna": "Personaje",
    "Walin": "Personaje",
    "Wan ShaiLu": "Personaje",
    "Wax": "Personaje",
    "Wayne": "Personaje",
    "Wellen": "Personaje",
    "Wellid": "Personaje",
    "Yalb": "Personaje",
    "Yanagawn": "Personaje",
    "Ym": "Personaje",
    "Yumi": "Personaje",
    "Zane": "Personaje",
    "Kushkam": "Personaje",
    "Alomancia": "Concepto",
    "Potenciación": "Concepto",
    "Luz tormentosa": "Concepto",
    "Aliento": "Concepto",
    "Dor": "Concepto",
    "Esfera": "Concepto",
    "Cosmere": "Concepto",
    "Ambición": "Personaje",
    "Armonía": "Personaje",
    "Autonomía": "Personaje",
    "Capricho": "Personaje",
    "Conservación": "Personaje",
    "Cultivación": "Personaje",
    "Devoción": "Personaje",
    "Dominio": "Personaje",
    "Dotación": "Personaje",
    "Honor": "Personaje",
    "Invención": "Personaje",
    "Odium": "Personaje",
    "Piedad": "Personaje",
    "Raciocinio": "Personaje",
    "Ruina": "Personaje",
    "Valentía": "Personaje",
    "Virtuosismo": "Personaje",
    "Ashyn": "Concepto",
    "Bjendal": "Concepto",
    "Braize": "Concepto",
    "Cántico": "Concepto",
    "Dhatri": "Concepto",
    "Komashi": "Concepto",
    "Lumar": "Concepto",
    "Mythos": "Concepto",
    "Nalthis": "Concepto",
    "Obrodai": "Concepto",
    "Primero del Sol": "Concepto",
    "Roshar": "Concepto",
    "Scadrial": "Concepto",
    "Sel": "Concepto",
    "Taldain": "Concepto",
    "Treno": "Concepto",
    "UTol": "Concepto",
    "Vax": "Concepto",
    "Yolen": "Concepto",
    "Adonalsium": "Concepto",
    "Fragmentación": "Concepto",
    "Esquirla del Amanecer": "Concepto",
    "Astilla": "Concepto",
    "Éter": "Concepto",
    "Teoría Realmática": "Concepto",
    "Investidura": "Concepto",
    "Arte Investida": "Concepto",
    "Intención": "Personaje",
    "Conexión": "Personaje",
    "Identidad": "Personaje",
    "Fortuna": "Personaje",
    "Redespíritu": "Concepto",
    "Eje": "Concepto",
    "Perpendicularidad": "Concepto",
    "Saltamundos": "Concepto",
    "Lasca": "Concepto",
    "Iniciación": "Concepto",
    "Resonancia": "Concepto",
    "Khriss": "Concepto",
    "Ire": "Concepto",
    "Sangre Espectral": "Concepto",
    "Luzdeplata": "Concepto",
}